[package]
name = "ray-tracing-in-one-weekend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rayon = "1.5.3"
indicatif = {version = "0.17.1", features = ["rayon"]}
image = "0.24.4"
clap = { version = "4.0.18", features = ["derive"] }
